from django.urls import path
from . import views

urlpatterns = [
    path('',views.homepageview),
    path('home',views.homepageview),
    path('about',views.aboutpageview), 
    path('contact',views.contactpageview),
    path('contactprocess',views.contactprocess),
    path('cake',views.contactpageview),
    path('cake/ahmedabad',views.contactpageview),
    path('cake/rajkot',views.contactpageview),
    path('shop',views.shoppage), 
    path('saveSession',views.saveSessionData),
    path('getSession',views.getSessionData),
    path('getSession2',views.getSessionData2), 
    path('removeSession',views.deleteSessionData),
    path('login',views.loginpage),
    path('loginprocess',views.loginprocess),
    path('dashboard',views.dashboard),
    path('logout',views.logout),
    path('maildemo',views.mailsenddemo),
    path('addstudent',views.addstudentform),
    path('add-student-process',views.addstudentformprocess),
    path('display-student',views.displayStudent),
    path('delete-student/<int:id>',views.deleteStudent),
    path('add-category',views.add_category, name='add_category'),
    path('display-category',views.display_category, name='display_category'),
    path('delete-category/<int:id>',views.delete_category, name='delete_category'),
    path('edit-category/<int:id>',views.edit_category, name='edit_category'),
    path('user_login', views.user_login_view, name='login'),
    path('user_register/', views.user_register_view, name='register'),
    path('user_home/', views.user_home_view, name='home'),
    path('user_logout/', views.user_logout_view, name='logout'),
    path('product', views.displayProduct, name='product'),
]